src/main/java/SystemManagement/MenuManagerBean.java
package SystemManagement;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;

/**
 * Created by romainjulien on 22/07/2016.
 */
@ManagedBean(name = "MenuManager", eager = true)
@SessionScoped
public class MenuManagerBean {

    private String menuSelected = "my-projects";

    public MenuManagerBean() {}

    public boolean isMenuSelected(String menu) {
        return menuSelected.equals(menu);
    }

    public String getMenuSelected() { return menuSelected; }

    public void setMenuSelected(String menuSelected) {
        this.menuSelected = menuSelected;
    }

    public String getHeaderTitle() {
        switch (menuSelected) {
            case "my-projects":
                return "My Projects";
            case "shared-projects":
                return "Shared projects";
            case "trash":
                return "Trash";
            default:
                break;
        }
        return null;
    }

    public String getIncludePage() {
        switch (menuSelected) {
            case "my-projects":
                return "my-projects-content-page.xhtml";
            case "shared-projects":
                return "my-projects-content-page.xhtml";
            case "trash":
                return "trash-content-page.xhtml";
            default:
                break;
        }
        return null;
    }

    public void resetMenuSelected() {
        menuSelected = "my-projects";
    }

}

web/pages/home/home.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">
<f:view>
    <h:head>
        <title>Prototype</title>
        <link rel="stylesheet" type="text/css" href="../../resources/css/style.css"/>
        <link rel="stylesheet" type="text/css" href="../../resources/css/home/home.css"/>
        <link rel="stylesheet" type="text/css" href="../../resources/css/home/project-content.css"/>
        <link rel="stylesheet" type="text/css" href="../../resources/css/home/new-project.css"/>
        <link rel="stylesheet" type="text/css" href="../../resources/css/home/drop-down.css"/>

        <script language="JavaScript" type="text/javascript" src="../../resources/js/jquery-1.12.3.js"></script>
        <script language="JavaScript" type="text/javascript" src="../../resources/js/home.js"></script>
        <script language="JavaScript" type="text/javascript" src="../../resources/js/project-factory.js"></script>

    </h:head>
    <h:body>

        <!--TODO: make sure this page is accessed after the user login/signup otherwise an error occurs-->

        <div id="header-wrapper">
            <div id="header">
                <h:graphicImage id="logo" value="../../resources/img/logo-thesis.png"/>

                <div id="user-account">
                    <div id="user-icon">
                        <p>#{ActiveUser.activeUser.initials}</p>
                    </div>
                    <div id="user-info">
                        <p>#{ActiveUser.activeUser.fullName}</p>
                        <h:form id="signout">
                            <h:commandLink value="Sign Out" action="#{ActiveUser.signOut}">
                                <f:ajax render="@none"/>
                            </h:commandLink>
                        </h:form>
                    </div>
                    <p id="hidden-user-id">#{ActiveUser.activeUser.id}</p>
                </div>
            </div>
        </div>
        <div id="main-wrapper">
            <div id="main">

                <h:form id="menu">
                    <div id="new-project">
                        <h:outputLink value="#" styleClass="button" onclick="showNewProjectModal()">New Project</h:outputLink>
                    </div>

                    <f:ajax render=":menu :main-content" onevent="handleRenderMenuChanges">
                        <div class="menu-item">
                            <img src="../../resources/img/Folder-Icon-o.png" alt="icon" />
                            <h:commandLink value="My Projects" action="#{MenuManager.setMenuSelected('my-projects')}"
                                    styleClass="#{MenuManager.isMenuSelected('my-projects') ? 'menu-selected' : ''}" >
                                <f:actionListener binding="#{ProjectManagement.setProjectSelected(null)}"/>
                            </h:commandLink>
                        </div>
                        <div class="menu-item">
                            <img src="../../resources/img/Folder-Icon-o.png" alt="icon" />
                            <h:commandLink
                                    value="Shared Projects" action="#{MenuManager.setMenuSelected('shared-projects')}"
                                    styleClass="#{MenuManager.isMenuSelected('shared-projects') ? 'menu-selected' : ''}">
                                <f:actionListener binding="#{ProjectManagement.setProjectSelected(null)}"/>
                            </h:commandLink>
                        </div>
                        <div class="menu-item">
                            <img src="../../resources/img/Trash-Icon-o.png" alt="icon" />
                            <h:commandLink
                                    value="Trash" action="#{MenuManager.setMenuSelected('trash')}"
                                    styleClass="#{MenuManager.isMenuSelected('trash') ? 'menu-selected' : ''}">
                                <f:actionListener binding="#{ProjectManagement.setProjectSelected(null)}"/>
                            </h:commandLink>
                        </div>
                    </f:ajax>
                </h:form>

                <h:panelGroup id="main-content" layout="block">
                    <ui:include src="#{MenuManager.includePage}" />
                </h:panelGroup>

            </div>
        </div>

        <h:panelGroup id="new-project-block-view" layout="block">
            <ui:include src="include/new-project.xhtml" />
        </h:panelGroup>

        <div id="invisible-overlay" onclick="hideAllDropDown()"></div>

        <h:commandButton id="reset-menu-selected" value="hidden" action="#{MenuManager.resetMenuSelected()}" >
            <f:ajax />
        </h:commandButton>

    </h:body>
</f:view>
</html>

web/pages/home/my-projects-content-page.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">
    <h:panelGroup id="header-bar-projects" styleClass="header-bar-projects" layout="block">
        <h1>
            <h:outputText value="#{MenuManager.headerTitle}" />
            <h:outputText value=" > #{ProjectManagement.projectSelected.projectName}"
                          rendered="#{not empty ProjectManagement.projectSelected}" />
        </h1>

        <h:outputLink styleClass="ide-link" value="../ide/ide.xhtml" rendered="#{not empty ProjectManagement.projectSelected}" >
            <h:graphicImage value="../../resources/img/View-Icon-o.png" />
        </h:outputLink>

        <h:panelGroup styleClass="project-selected-menu" layout="block"
                      rendered="#{not empty ProjectManagement.projectSelected}">
            <img src="../../resources/img/Group-Icon-o.png" alt="collaborators" onclick="toggleCollaboratorsDropDown()"/>
            <h:panelGroup styleClass="collaborators-drop-down dropdown" layout="block">
                <ui:include src="include/collaborators-drop-down.xhtml" />
            </h:panelGroup>
            <img src="../../resources/img/Snapshot-Icon-o.png" alt="snapshots" onclick="toggleSnapshotsDropDown()"/>
            <h:panelGroup styleClass="snapshots-drop-down dropdown" layout="block">
                <ui:include src="include/snapshots-drop-down.xhtml" />
            </h:panelGroup>
            <img src="../../resources/img/Tool-Icon-o.png" alt="settings" />
        </h:panelGroup>
    </h:panelGroup>

    <h:form id="my-project-list" styleClass="project-list" layout="block">
        <ui:repeat value="#{SystemManagement.myProjectList}" var="project">
            <div class="project-block">
                <h:commandLink action="#{ProjectManagement.setProjectSelected(project)}">
                    <h:graphicImage value="../../resources/img/folder.png" />
                    <f:ajax render=":header-bar-projects" />
                </h:commandLink>
                <h3>#{project.projectName}</h3>
            </div>
        </ui:repeat>
    </h:form>
    <!--<div style="clear: both"></div>-->

    <h:form id="shared-project-list" styleClass="project-list" layout="block">
        <ui:repeat value="#{SystemManagement.sharedProjectList}" var="sharedProject">
            <div class="project-block">
                <h:commandLink action="#{ProjectManagement.setProjectSelected(sharedProject)}">
                    <h:graphicImage value="../../resources/img/folder.png" />
                    <f:ajax render=":header-bar-projects" />
                </h:commandLink>
                <h3>#{sharedProject.projectName}</h3>
            </div>
        </ui:repeat>
    </h:form>

    <h:commandButton id="refresh-project-list-button" >
        <f:ajax render=":my-project-list"/>
    </h:commandButton>

</ui:composition>

web/pages/home/trash-content-page.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">
    <h:panelGroup id="header-bar-trash" styleClass="header-bar-projects" layout="block">
        <h1>
            <h:outputText value="#{MenuManager.headerTitle}" />
        </h1>
    </h:panelGroup>
</ui:composition>